### ISSUE TITLE
Requesting access to Cluster

### ISSUE THREAD

**Issue by ChandniJha04** [Dynatrace-India/DT-Transform-Managed-Lab#11]
## Why do you need the access?
For Learning and R&D purpose

## What type of access required?
Currently will require environment access only

**Comment by theharithsa** [comment]
Hi Chandni, 

Than you for raising issue with us requesting access to the lab environment. You will get the access within next 1 hour. Keep an eye on your mailbox. 

Regards, 
VH

**Comment by theharithsa** [comment]
Access has been granted. You have access to Transform Managed Lab. 
![image](https://user-images.githubusercontent.com/14597214/119148127-d7377380-ba69-11eb-82e5-69252d86df5b.png)
