### ISSUE TITLE
TIAA Batch 2 - Create VMs for Training Purpose

### ISSUE THREAD

**Issue by theharithsa** [Dynatrace-India/DT-Transform-Managed-Lab#12]
### Follow the instructions below while creating VMs and environments.

@rakshaKrishna 
#### Creating Virtual Machines in Azure DevTest Labs
1. Attached excel sheet contains the details of the user who wants to be given access for created VM
2. Each user must have at least 2 VMs allotted.
3. Attendees list has been mailed to Dynatrace ID.
4. Once it is done please close the issue. 
--------------------------------------------------------------------------------------------------------

**Comment by rakshaKrishna** [comment]
VMs created and mailed the same to Attendees.
