### ISSUE TITLE
Requesting access to Cluster

### ISSUE THREAD

**Issue by Kannanjailkhani** [Dynatrace-India/DT-Transform-Managed-Lab#22]
## Why do you need the access?
To get familiarized with tools at cluster side. 

## What type of access required?
Demo / Read / Edit

**Comment by theharithsa** [comment]
Hi Kanan, 
Thank you for reaching out and requesting access to our transform lab. As a part of beginner access you will be provided an environment where you can use it for your learning purposes. Your access will be initialed in next 15 mins. Please check your email. 

Regards, 
Vishruth Harithsa

**Comment by theharithsa** [comment]
Access is granted
