### ISSUE TITLE
Requesting access to Cluster

### ISSUE THREAD

**Issue by BhagatOmkar** [Dynatrace-India/DT-Transform-Managed-Lab#27]
## Why do you need the access?
For R&D as well as to test some configurations before applying them in customer's environment.

## What type of access required?
Need Environment access only.

**Comment by theharithsa** [comment]
Hi Omkar, 
Your access has been given. 
Feel free to use it and also use SSO based authetication for smoother access, 
follow the steps here. https://github.com/Dynatrace-India/DT-Transform-Managed-Lab/blob/main/SSO/users.md
