### ISSUE TITLE
To test Installation user change across Clusters #15Requesting access to Cluster

### ISSUE THREAD

**Issue by ANANDS80** [Dynatrace-India/DT-Transform-Managed-Lab#31]
## Why do you need the access?
- We have been using op_2062_appmon with UID 998 and Groupname op_2062_appmon with GUID 1003 in all cluster nodes in the ICICI environment.

- Customer having security compliance to use the same ID for server and node installation and requesting us to change the existing ID op_2062_appmon to op_2062 for Node installation.

### Steps
1. We received the fix from our support
disable backups for each node:

    ```sudo /opt/dynatrace-managed/launcher/dynatrace.sh stop```
    ```sudo usermod -u #new_user_id# dynatrace```
    ```sudo chown dynatrace:dynatrace /opt/dtrun/validate```
    ```sudo chown dynatrace:dynatrace /opt/dtrun/run```
    ```sudo /opt/dynatrace-managed/installer/reconfigure.sh```

2. Once done with cluster nodes, reset backups owner

    ```sudo chown -R dynatrace /path/to/shared/backups```

3. Enable cluster backups

But we need to test this before we go into the LIVE environment

## What type of access required?
Admin access to the cluster and access to cluster nodes as well.

**Comment by ANANDS80** [comment]
We need 3 cluster nodes and one new node to add after change the user name

**Comment by ANANDS80** [comment]
We need 3 cluster nodes and one new node to add after change the user name

**Comment by theharithsa** [comment]
Thanks for raising the issue, Anand. 
We will provide you with access to Cluster nodes and CMC.

Please specify the people who required the access. Is it only for you?

**Comment by theharithsa** [comment]
Hi @ANANDS80, 
Is this issue resolved or the workaround was successful? 
Please mention the details in the issue about that and close it from your side.

**Comment by ANANDS80** [comment]
Hi

Issue still not resolved ,need some more investigation.

Regards
Anand S
