### ISSUE TITLE
Required VM for Learning Purpose

### ISSUE THREAD

**Issue by fakrukhan47** [Dynatrace-India/DT-Transform-Managed-Lab#32]
## What are the resources you need?
RHEL server on Azure.

## Why do you need it?
test and run keptn before installing in Production

## How long do you need it?
would need it for 6 months.

## Severity of the requirement
Critical

## Configuration
8 Core, 30 GB RAM and 100GB disk.

**Comment by theharithsa** [comment]
Hi Fakruddin, 
As you requested, I have created a VM and sent it to you in an email. Please find it in your inbox. 
![image](https://user-images.githubusercontent.com/14597214/122719855-6368d080-d28c-11eb-8e60-f5e023408070.png)

Thank You. I hope this helps.
