### ISSUE TITLE
Requesting access to Cluster

### ISSUE THREAD

**Issue by pavankumar98** [Dynatrace-India/DT-Transform-Managed-Lab#33]
Hi Vishruth,

Please give access to https://lab.dt-transform.com/ for pavan.babu@dynatrace.com.

Best,
Pavan Kumar.

**Comment by theharithsa** [comment]
Hi Pavan, 
Your environment is added and given access to you. Please use the invite you received from **Microsoft Invitations** and accept it to start accessing your lab. Please use SSO to log in.
