### ISSUE TITLE
Required VM for Learning Purpose

### ISSUE THREAD

**Issue by ajbhi1312** [Dynatrace-India/DT-Transform-Managed-Lab#8]
## What are the resources you need?
Please mention the service names that you need in Azure or GCP
Azure - Virtual machine & GCP - Compute Engine

## Why do you need it?
I need it for testing purpose, as I got numerous different of the client requirements and this will be very useful to test any solutions.  

## How long do you need it?
I will need the access for couple of months to close on the deployment part of my project. 

## Severity of the requirement
 ```Medium```

## Configuration
Small configuration - 2 Core CPU & 4 GB RAM along with minimum HDD

**Comment by theharithsa** [comment]
Thanks for raising the request, Abhijay.
I will provide you the VMs and the credentials to those VMs will be shared with you to your email ID. 

Regards, 
VH
